# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_UAV(object):
    def setupUi(self, UAV):
        UAV.setObjectName("UAV")
        UAV.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(UAV)
        self.centralwidget.setObjectName("centralwidget")
        self.front = QtWidgets.QPushButton(self.centralwidget)
        self.front.setGeometry(QtCore.QRect(120, 90, 60, 60))
        self.front.setStyleSheet("border-image: url(:/src/front.png);")
        self.front.setText("")
        self.front.setObjectName("front")
        self.left = QtWidgets.QPushButton(self.centralwidget)
        self.left.setGeometry(QtCore.QRect(60, 150, 60, 60))
        self.left.setStyleSheet("border-image: url(:/src/left.png);")
        self.left.setText("")
        self.left.setObjectName("left")
        self.right = QtWidgets.QPushButton(self.centralwidget)
        self.right.setGeometry(QtCore.QRect(180, 150, 60, 60))
        self.right.setStyleSheet("border-image: url(:/src/right.png);")
        self.right.setText("")
        self.right.setObjectName("right")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(120, 210, 60, 60))
        self.back.setStyleSheet("border-image: url(:/src/back.png);")
        self.back.setText("")
        self.back.setObjectName("back")
        self.down = QtWidgets.QPushButton(self.centralwidget)
        self.down.setGeometry(QtCore.QRect(180, 270, 60, 60))
        self.down.setStyleSheet("border-image: url(:/src/down.png);")
        self.down.setText("")
        self.down.setObjectName("down")
        self.up = QtWidgets.QPushButton(self.centralwidget)
        self.up.setGeometry(QtCore.QRect(60, 270, 60, 60))
        self.up.setStyleSheet("border-image: url(:/src/up.png);")
        self.up.setText("")
        self.up.setObjectName("up")
        self.pos_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pos_input.setGeometry(QtCore.QRect(120, 390, 113, 26))
        self.pos_input.setObjectName("pos_input")
        self.ori_input = QtWidgets.QLineEdit(self.centralwidget)
        self.ori_input.setGeometry(QtCore.QRect(120, 430, 113, 26))
        self.ori_input.setObjectName("ori_input")
        self.pos_label = QtWidgets.QLabel(self.centralwidget)
        self.pos_label.setGeometry(QtCore.QRect(70, 390, 54, 26))
        self.pos_label.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.pos_label.setObjectName("pos_label")
        self.ori_label = QtWidgets.QLabel(self.centralwidget)
        self.ori_label.setGeometry(QtCore.QRect(70, 430, 54, 26))
        self.ori_label.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.ori_label.setObjectName("ori_label")
        self.send = QtWidgets.QPushButton(self.centralwidget)
        self.send.setGeometry(QtCore.QRect(110, 480, 80, 26))
        self.send.setObjectName("send")
        self.camera_img = QtWidgets.QLabel(self.centralwidget)
        self.camera_img.setGeometry(QtCore.QRect(430, 30, 220, 220))
        self.camera_img.setStyleSheet("image: url(:/src/camera.jpg);")
        self.camera_img.setText("")
        self.camera_img.setObjectName("camera_img")
        self.slam_img = QtWidgets.QLabel(self.centralwidget)
        self.slam_img.setGeometry(QtCore.QRect(430, 300, 220, 220))
        self.slam_img.setStyleSheet("image: url(:/src/map.jpeg);")
        self.slam_img.setText("")
        self.slam_img.setObjectName("slam_img")
        self.camera_label = QtWidgets.QLabel(self.centralwidget)
        self.camera_label.setGeometry(QtCore.QRect(510, 260, 54, 26))
        self.camera_label.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.camera_label.setObjectName("camera_label")
        self.slam_label = QtWidgets.QLabel(self.centralwidget)
        self.slam_label.setGeometry(QtCore.QRect(510, 530, 54, 26))
        self.slam_label.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.slam_label.setObjectName("slam_label")
        UAV.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(UAV)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        UAV.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(UAV)
        self.statusbar.setObjectName("statusbar")
        UAV.setStatusBar(self.statusbar)

        self.retranslateUi(UAV)
        QtCore.QMetaObject.connectSlotsByName(UAV)

    def retranslateUi(self, UAV):
        _translate = QtCore.QCoreApplication.translate
        UAV.setWindowTitle(_translate("UAV", "MainWindow"))
        self.pos_label.setText(_translate("UAV", "<html><head/><body><p align=\"center\"><span style=\" color:#ececec;\">POS</span></p></body></html>"))
        self.ori_label.setText(_translate("UAV", "<html><head/><body><p align=\"center\"><span style=\" color:#ececec;\">ORI</span></p></body></html>"))
        self.send.setText(_translate("UAV", "SEND"))
        self.camera_label.setText(_translate("UAV", "<html><head/><body><p align=\"center\"><span style=\" color:#ececec;\">Camera</span></p></body></html>"))
        self.slam_label.setText(_translate("UAV", "<html><head/><body><p align=\"center\"><span style=\" color:#ececec;\">SLAM</span></p></body></html>"))

# import Image_rc
